# Student Alcohol Consumption

### Introduction:

This time you will download a dataset from the UCI.

### Step 1. Import the necessary libraries

In [1]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv).

### Step 3. Assign it to a variable called df.

In [2]:
url = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv'
df = pd.read_csv(url)

### Step 4. For the purpose of this exercise slice the dataframe from 'school' until the 'guardian' column

In [8]:
df = df.loc[:,'school':'guardian']
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother
4,GP,F,16,U,GT3,T,3,3,other,other,home,father
...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,course,other
391,MS,M,17,U,LE3,T,3,1,services,services,course,mother
392,MS,M,21,R,GT3,T,1,1,other,other,course,other
393,MS,M,18,R,LE3,T,3,2,services,other,course,mother
394,MS,M,19,U,LE3,T,1,1,other,at_home,course,father

### Step 5. Create a lambda function that will capitalize strings.

In [9]:
cap_string = lambda x: x.upper()

### Step 6. Capitalize both Mjob and Fjob

In [12]:
df.Mjob = df.Mjob.apply(cap_string)
df.Fjob = df.Fjob.apply(cap_string)
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,18,U,GT3,A,4,4,AT_HOME,TEACHER,course,mother
1,GP,F,17,U,GT3,T,1,1,AT_HOME,OTHER,course,father
2,GP,F,15,U,LE3,T,1,1,AT_HOME,OTHER,other,mother
3,GP,F,15,U,GT3,T,4,2,HEALTH,SERVICES,home,mother
4,GP,F,16,U,GT3,T,3,3,OTHER,OTHER,home,father
...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,SERVICES,SERVICES,course,other
391,MS,M,17,U,LE3,T,3,1,SERVICES,SERVICES,course,mother
392,MS,M,21,R,GT3,T,1,1,OTHER,OTHER,course,other
393,MS,M,18,R,LE3,T,3,2,SERVICES,OTHER,course,mother
394,MS,M,19,U,LE3,T,1,1,OTHER,AT_HOME,course,father

### Step 7. Print the last elements of the data set.

In [13]:
df.tail(1)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
394,MS,M,19,U,LE3,T,1,1,OTHER,AT_HOME,course,father

### Step 8. Did you notice the original dataframe is still lowercase? Why is that? Fix it and capitalize Mjob and Fjob.

In [15]:
# the original is not lowercase, you mad lad
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian
0,GP,F,18,U,GT3,A,4,4,AT_HOME,TEACHER,course,mother
1,GP,F,17,U,GT3,T,1,1,AT_HOME,OTHER,course,father
2,GP,F,15,U,LE3,T,1,1,AT_HOME,OTHER,other,mother
3,GP,F,15,U,GT3,T,4,2,HEALTH,SERVICES,home,mother
4,GP,F,16,U,GT3,T,3,3,OTHER,OTHER,home,father

### Step 9. Create a function called majority that returns a boolean value to a new column called legal_drinker (Consider majority as older than 17 years old)

In [16]:
def isMajority(x):
  return x > 17

In [17]:
df['legal_drinker'] = isMajority(df.age)
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,legal_drinker
0,GP,F,18,U,GT3,A,4,4,AT_HOME,TEACHER,course,mother,True
1,GP,F,17,U,GT3,T,1,1,AT_HOME,OTHER,course,father,False
2,GP,F,15,U,LE3,T,1,1,AT_HOME,OTHER,other,mother,False
3,GP,F,15,U,GT3,T,4,2,HEALTH,SERVICES,home,mother,False
4,GP,F,16,U,GT3,T,3,3,OTHER,OTHER,home,father,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,SERVICES,SERVICES,course,other,True
391,MS,M,17,U,LE3,T,3,1,SERVICES,SERVICES,course,mother,False
392,MS,M,21,R,GT3,T,1,1,OTHER,OTHER,course,other,True
393,MS,M,18,R,LE3,T,3,2,SERVICES,OTHER,course,mother,True
394,MS,M,19,U,LE3,T,1,1,OTHER,AT_HOME,course,father,True

### Step 10. Multiply every number of the dataset by 10.
##### I know this makes no sense, don't forget it is just an exercise

In [24]:
for col in df.columns:
  if df[col].dtype == 'int64':
    df[col] = df[col] *10
df

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,legal_drinker
0,GP,F,180,U,GT3,A,40,40,AT_HOME,TEACHER,course,mother,True
1,GP,F,170,U,GT3,T,10,10,AT_HOME,OTHER,course,father,False
2,GP,F,150,U,LE3,T,10,10,AT_HOME,OTHER,other,mother,False
3,GP,F,150,U,GT3,T,40,20,HEALTH,SERVICES,home,mother,False
4,GP,F,160,U,GT3,T,30,30,OTHER,OTHER,home,father,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,200,U,LE3,A,20,20,SERVICES,SERVICES,course,other,True
391,MS,M,170,U,LE3,T,30,10,SERVICES,SERVICES,course,mother,False
392,MS,M,210,R,GT3,T,10,10,OTHER,OTHER,course,other,True
393,MS,M,180,R,LE3,T,30,20,SERVICES,OTHER,course,mother,True
394,MS,M,190,U,LE3,T,10,10,OTHER,AT_HOME,course,father,True